config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  devise_for :users

  resources :dashboard, only: [:index]
  resources :expenses, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :expenses

  validates :name, uniqueness: true

end

app/models/expense.rb
class Expense < ApplicationRecord

  validates :user_id, presence: true
  validates :category, presence: true
  validates :transaction_type, presence: true
  validates :amount, numericality: { greater_than: 0}
  validates :concept, presence: true
  before_create :data_cant_be_nil

  belongs_to :user
  belongs_to :category
  belongs_to :transaction_type

  scope :last_six_months, -> { where("date >= ?", 6.months.ago)}
  scope :this_month, -> { where("date >= ?", 0.month.ago.beginning_of_month)}
  scope :by_category_this_month, -> { this_month.group_by { |expense| expense.category.name}}
  scope :by_category_last_six_month, -> { last_six_months.group_by { |expense| expense.category.name}}
  scope :by_transaction_this_month, -> { this_month.group_by { |expense| expense.transaction_type.name}}
  scope :by_transaction_last_six_month, -> { last_six_months.group_by { |expense| expense.transaction_type.name} }
  scope :last_month, -> { where("date >= ? and date >= ?", 1.month.ago.beginning_of_month, 1.month.ago.end_of_month)}
  scope :amount_last_month, -> {last_month.pluck(:amount).sum }
  scope :amount_this_month, -> {this_month.pluck(:amount).sum }
  scope :daily_expenses, -> {where('date >=?', 1.day.ago.end_of_day)}
  scope :yesterday_expenses, -> {where('date between ? and ?', 1.day.ago.beginning_of_day, 1.day.ago.end_of_day)}
  scope :last_two_months, -> { where("date >= ?", 1.month.ago.beginning_of_month)}

  def data_cant_be_nil
    if self.date.nil?
      self.date = Time.now
    end
  end
end

app/models/transaction_type.rb
class TransactionType < ApplicationRecord

  has_many :expenses

  validates :name, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :expenses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @handler = DashboardHandler.new(Expense.all)
    @today_expenses = @handler.today_expenses
    @yesterday_expenses = @handler.yesterday_expenses
    @this_month_expenses = @handler.this_month_expenses
    @last_month_expenses = @handler.last_month_expenses
  end

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    transaction_type = params["transaction_type"]
    category = params["category"]
    if transaction_type && !category
      @expenses = Expense.joins(:transaction_type).where("transaction_types.name = ?", transaction_type.capitalize)
    elsif category && !transaction_type
      @expenses = Expense.joins(:category).where("categories.name = ?", category.capitalize)
    elsif category && transaction_type
      @expenses = Expense.joins(:transaction_type, :category).where("transaction_types.name = ? AND categories.name", transaction_type.capitalize, category.capitalize)
    else
      @expenses = Expense.order(date: :desc)
    end


    @transaction_type = TransactionType.all
    @category = Category.all
    # @months =
    #   if expenses.last.date.month - expenses.first.date.month <  12

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @expenses, status: :ok }
      format.js { render partial: "expenses_list", locals: { expenses: @expenses}}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/dashboard/index.html.erb
<%= render 'shared/navbar' %>
<div class="container">
 <section class="d-flex justify-content-around">
   <div id="stats" class="p-2">
     <p><%= number_to_currency(@today_expenses) %></p>
     <span>Today</span>
   </div>
   <div id="stats" class="p-2">
     <p><%= number_to_currency(@yesterday_expenses) %></p>
     <span>Yesterday</span>
   </div>
   <div id="stats" class="p-2">
     <p><%= number_to_currency(@this_month_expenses) %></p>
     <span>This Month</span>
   </div>
   <div id="stats" class="p-2">
     <p><%= number_to_currency(@last_month_expenses) %></p>
     <span>Last Month</span>
   </div>
 </section>
 <section class="d-flex justify-content-around flex-wrap" id="Graph_tables">
   <div class="graphs" id='last_six_months'><%= column_chart @handler.last_six_month.joins(:transaction_type).group('transaction_types.name').group_by_month(:date, format: "%b").sum(:amount), stacked: true %></div>
   <div class="graphs" id='By_day'><%= column_chart @handler.this_month.joins(:transaction_type).group('transaction_types.name').group_by_day(:date, format: "%d").sum(:amount) %></div>
   <div class="graphs" id="By_category"><%= pie_chart @handler.this_month.joins(:transaction_type).group('transaction_types.name').count %></div>
   <div class="graphs" id="Accumulated"><%= area_chart [{name: "April", data: @handler.last_month.group_by_day(:date).sum(:amount)}, {name: "May", data: @handler.this_month.group_by_day(:date).sum(:amount)}] %> </div>
 </section>
</div>

app/views/expenses/_expenses_list.html.erb
<section class="expenses-list">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Concept</th>
        <th scope="col">Category</th>
        <th scope="col">Value</th>
      </tr>
    </thead>
    <tbody>
      <% expenses.each do |expense| %>
      <tr>
        <th class="show_date"><%= expense.date.strftime("%d %b") %></th>
        <td>
          <p class="transactiontable text-muted"><%= expense.transaction_type.name %></p>
          <%= expense.concept %>
        </td>
        <td><%= expense.category.name %></td>
        <td><%= number_to_currency(expense.amount) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/expenses/index.html.erb
<%= render 'shared/navbar' %>
<div class="container">
  <div class="row">
    <div class="col-3">
      <div class="transaction-type">
        <h4>Transaction type</h4>
        <% @transaction_type.each do |transaction_type| %>
        <ul class="list-group">
          <li class="transaction_type list-group-item" id= <%= transaction_type.name %> ><%= transaction_type.name %></li>
        </ul>
        <% end %>
      </div>
      <br>
      <div class="category-type">
        <h4>Category</h4>
        <% @category.each do |category| %>
        <ul class="list-group">
          <li class="category list-group-item" id= <%= category.name %> ><%= category.name %></li>
        </ul>
        <% end %>
      </div>
    </div>
    <div class="col-9">
      <section class="d-flex justify-content-around">
        <div id="stats" class="p-2">
          <p><%=  %></p>
          <span>Total</span>
        </div>
        <div id="stats" class="p-2">
          <p>$1.300.000</p>
          <span>Transactions</span>
        </div>
        <div id="stats" class="p-2">
          <p>$1.300.000</p>
          <span>Average</span>
        </div>
      </section>
      <div id="margin_buttons" class="d-flex justify-content-between">
          <button class="btn btn-dark"><%= link_to ' + New Expense ', expenses_path, :class => "nav-item nav-link active" %></button>
          <div class="dropdown">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Dropdown button
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="#">Link 1</a>
              <a class="dropdown-item" href="#">Link 2</a>
              <a class="dropdown-item" href="#">Link 3</a>
            </div>
          </div>
      </div>
      <div class="expense_table">
        <%= render partial: 'expenses_list', locals: { expenses: @expenses} %>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function() {
    $(".transaction_type").on('click', function(e){
      $(".active").removeClass("active");
      var filter = this.id;
      var tag_button = $(this);
      tag_button.addClass("active");
      var param = {"transaction_type": filter };
      e.preventDefault();
      $.ajax({
        type: "GET",
        url: "/expenses.js",
        dataType: "html",
        data: param,
        success: function(response) {
          $(".expense_table").empty();
          $(".expense_table").html(response);
        }
      });
    });
  });
  $(document).ready(function() {
    $(".category").on('click', function(e){
      $(".active").removeClass("active");
      var filter = this.id;
      var tag_button = $(this);
      tag_button.addClass("active");
      var param = {"category": filter };
      e.preventDefault();
      $.ajax({
        type: "GET",
        url: "/expenses.js",
        dataType: "html",
        data: param,
        success: function(response) {
          $(".expense_table").empty();
          $(".expense_table").html(response);
        }
      });
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-expensify">
 <div class="container">
   <a class="navbar-brand"><%= image_tag("bm_logo.png", class: "img-responsive", id: "Budget_manager-logo") %></a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
     <div class="navbar-nav">
       <a> <%= link_to 'Dashboard', dashboard_index_path, :class => "nav-item nav-link active" %><span class="sr-only">(current)</span></a>
       <a> <%= link_to 'Expenses', expenses_path, :class => "nav-item nav-link active" %><span class="sr-only">(current)</span></a>
     </div>
   </div>
 </div>
</nav>